### ISSUE TITLE
Make several hpcasts.com courses for LGCB

### ISSUE THREAD

**Issue by happypeter** [happypeter/LGCB#13]
here in LGCB, we cover, git, vim, bash... for beginners

each of them make a good hpcasts.com course.

**Comment by boredivan** [comment]
I visited hpcasts.com just now. It seems that this website is under building. 
Is there any connection between the two websites happycasts.com and hpcasts.com ?

**Comment by happypeter** [comment]
hpcasts.com will be a commercial site, we are going to sell programming courses there. sort of a lynda.com

**Comment by boredivan** [comment]
OK. I've heard lynda.com on petercorner before. What a great project it will be to construct such a website like that !
Is it a project of your company which you are working for ? May I know more about you ?

**Comment by happypeter** [comment]
Yes，it's a company, and there are several of us. hpcasts.com will be
commericial, but it also has to be fun, like github.com ：-）

If you want to be a video course maker, you are welcomed to  join us.

On Tue, Jan 8, 2013 at 7:02 PM, Ivan Zhou notifications@github.com wrote:

> OK. I've heard lynda.com on petercorner before. What a great project it
> will be to construct such a website like that !
> Is it a project of your company which you are working for ? May I know
> more about you ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/happypeter/LGCB/issues/13#issuecomment-11992953.

## 

Regards
Peter

happypeter.org http://happypeter.github.com/index.html

**Comment by boredivan** [comment]
Ha-ha. I'm just a student and I'm learning. 
However, I will pay attention to it. Good luck!

**Comment by happypeter** [comment]
hpcasts.com is now haoqicat.com
