### ISSUE TITLE
to pdf

### ISSUE THREAD

**Issue by happypeter** [happypeter/LGCB#33]
https://github.com/happypeter/LGCB/blob/gh-pages/tools/doc_gen.sh

这个里面的方案比较老了，可以不用 pandoc

**Comment by happypeter** [comment]
最终目标：执行一个脚本，我的 LGCB 这本书直接变成 pdf

这个任务比较复杂，所以我们分布来弄，首先: https://github.com/happypeter/LGCB/issues/34

**Comment by happypeter** [comment]
不必考虑 table 等其他复杂格式，只要能处理 LGCB 就行，不考虑通用性。

**Comment by billie66** [comment]
已经能够把目前 LGCB 的内容转换成 PDF 格式，但文档没有先后顺序，这个需要下一步完成

**Comment by billie66** [comment]
现在 LGCB 已经能按照顺序生成美观的 PDF 文档了

**Comment by happypeter** [comment]
great
