### ISSUE TITLE
三篇文章转出 pdf 书

### ISSUE THREAD

**Issue by happypeter** [happypeter/LGCB#34]
整个的 pdf 转换工作是很复杂的，这里先完成最简单地一步

给出三篇 kramdown 格式的 markdown 文档，没图片没表格，没有任何复杂格式，只有一个标题。

目标：自动生成目录和封面，转出成一本 pdf 书。

**Comment by happypeter** [comment]
这个过程中不要追求完美，如果生成目录的时候遇到特殊的困难，可以另提 issue。

**Comment by billie66** [comment]
目前任意数目的 GFM 格式的文档，都可以转成一本 PDF 书了。 cb896b5c36
