### ISSUE TITLE
按照文档先后顺序生成 PDF

### ISSUE THREAD

**Issue by billie66** [happypeter/LGCB#35]

**Comment by happypeter** [comment]
可以参考 jekyll blog 的思想，给每个 md 文件的文件名前签名加序号

00-intro.md 01-bash.md 02-git.md

**Comment by billie66** [comment]
@happypeter 就按照你的方法解决这个问题吧

**Comment by billie66** [comment]
给文件添加序号之后，对文件名进行排序，就可以生成正确顺序的 PDF 文档了。重命名文件的任务，可由   tools 目录下的 rename_file.rb 文件完成

**Comment by happypeter** [comment]
rename_file.rb 这个软件写得多余了，有看懂这个程序工作原理的时间，自己早就可以手动把文件重命名好了。

建议删除这个文件。

**Comment by billie66** [comment]
文件已经编号了
