### ISSUE TITLE
不能生成书籍目录

### ISSUE THREAD

**Issue by billie66** [happypeter/LGCB#36]
现在 LGCB 的内容虽然能生成一本书，但却没有生成目录。

**Comment by billie66** [comment]
这个主要是自动生成的 latex 文件格式有问题，比方说一级标题

``` md
# header
```

通过 kramdown 转换成 latex,

``` latex
\section*{header}
```

而这种格式的标题不能在目录中显示出来，正确格式是

``` latex
\section{header}
```

上述原理也适用于 chapter

**Comment by billie66** [comment]
需要运行两次 `xelatex lgcb.tex` 命令才能生成目录，这是什么情况？

**Comment by billie66** [comment]
LGCB 中的一级标题都是以三个 `#` 打头，这样生成的 PDF 目录很不好看，建议用 kramdown 的一级标题格式，以一个 `#` 打头。

**Comment by happypeter** [comment]
good

**Comment by billie66** [comment]
好消息，不用修改 LGCB 的标题级别就可以生成漂亮的目录了，kramdown 有一个选项 `header_offset` 可以控制生成的 latex 文本的标题级别，现在 LGCB 使用的是三级标题，通过把 `header_offset` 的值设置为 -3，就能生成一级标题的 latex 文本

```
:header_offset => -3
```

这个 issue 涉及到的另一个 kramdown 选项是 `auto_ids`，这个选项的值必须是 true 才行

```
:auto_ids => true
```

最后是必须运行两次 xelatex 命令才能生成合适的目录，这里的 *.tex 代表转换成的完整的 latex 文本

```
xelatex *.tex
```

贴一个参考链接 [kramdown options](http://kramdown.gettalong.org/rdoc/Kramdown/Options.html)
