### ISSUE TITLE
PDF 文档中显示图片

### ISSUE THREAD

**Issue by billie66** [happypeter/LGCB#37]

**Comment by billie66** [comment]
http://tex.stackexchange.com/questions/5433/can-i-use-an-image-located-on-the-web-in-a-latex-document

根据上面帖子的讨论，latex 只能处理本地的图片。kramdown 直接忽视下面的语句

```
![A Painting](http://commons.wikimedia.org/wiki/File:Pachydyptes_ponderosus.jpg)
```

kramdown 会转换下面的语句，dog.png 是本地一张图片

```
![](dog.png)
```

**Comment by billie66** [comment]
一个名为 demo.tex 的文件，使用了 latex 命令 immediate & write18，来执行外部命令

``` latex
\documentclass{article}
\usepackage{graphicx}
\usepackage{hyperref}

\begin{document}
\begin{figure}
\center
\immediate\write18{wget http://media.happycasts.net/pic/lgcb/peter_github.png}
\includegraphics[width=0.5\textwidth]{peter_github.png}
\end{figure}

\end{document}
```

首先通过 latex 命令下载网上的图片到本地，然后使用图片。不过需要用到下面的命令生成 PDF

```
xelatex --enable-write18 demo.tex
```

参考文档 http://tex.stackexchange.com/questions/20444/what-are-immediate-write18-and-how-does-one-use-them

**Comment by billie66** [comment]
这样的话，所有网上托管的图片必须下载到本地了

**Comment by billie66** [comment]
### 关于有的图片太宽，会溢出页面的问题

```
\includegraphics[width=10cm,height=10cm,keepaspectratio]{image}
```

暂时用这个方法对最大宽和高作一下限制。这种方法的问题是，如果图片的长和宽都很小，那么图片会被放大太多。不过相信这种太小的图片情况并不多见。可以在文档中规定一下，图片的最小高度和宽度的值。

---

另外，有一种备选方案：图片插入之前，先用 imagemagick 处理大图片，这样不但显示的时候不用设置长宽了，而且整个 pdf 文档也会小很多。不过毕竟要多处理一步，还是麻烦。

**Comment by billie66** [comment]
以上方案还是可以的

**Comment by billie66** [comment]
若图片太大，上面的规则就行不通了。LGCB 中的 peter.jpg 文件就比较大，把它转换成 png 格式就可以了

**Comment by happypeter** [comment]
尽量不要转换，太麻烦了。

**Comment by billie66** [comment]
现在设置的图片样式无法控制 peter.jpg 这张图片，即使把图片宽度缩小一半也不行

```
peter@goodcat:~$ file peter.jpg 
peter.jpg: JPEG image data, baseline, precision 0, 4360x460
```

转换成 png 格式后的大小

```
peter@goodcat:~$ file peter.png
peter.png: PNG image data, 460 x 460, 8-bit/color RGB, non-interlaced
```
