### ISSUE TITLE
代码块的显示问题

### ISSUE THREAD

**Issue by billie66** [happypeter/LGCB#38]
调整代码块的样式，还有处理溢出问题

**Comment by happypeter** [comment]
溢出部分要换行，换行要加指示符

**Comment by billie66** [comment]
用 latex  的 listings 包裹可以实现代码块换行

``` latex
\usepackage{listings}
\lstset{breaklines=true}
```

**Comment by billie66** [comment]
一些 latex 的小问题
http://wsong83.wordpress.com/2011/07/08/%E4%B8%80%E4%BA%9Blatex%E7%9A%84%E5%B0%8F%E9%97%AE%E9%A2%98/

**Comment by billie66** [comment]
listings 不支持 makefile 代码块

**Comment by billie66** [comment]
listings 支持 make，可以用 make 来代替 makefile
