### ISSUE TITLE
比较长的链接和 Email 会超出页面

### ISSUE THREAD

**Issue by billie66** [happypeter/LGCB#41]

**Comment by billie66** [comment]
可以试着更新 breakurl 宏包，看看能不能解决这个问题

**Comment by billie66** [comment]
xelatex 环境下，不能使用 breakurl 宏包，真是悲催！
http://bbs.ctex.org/forum.php?mod=viewthread&tid=75966

**Comment by billie66** [comment]
手动修改了一下 markdown 文件，让超出页面的链接和邮箱地址独自占用一行，progit 也是采取这样的方式，不过 progit 是自动检测链接，然后让链接独占一行显示

**Comment by happypeter** [comment]
这个方法还是可以的。

**Comment by billie66** [comment]
> 不过 progit 是自动检测链接，然后让链接独占一行显示

需要更正一下，progit 在文档中让比较长的链接独占一行，而不是后续处理的。

对于progit 中文版则使用了中文的断行方式。

progit 的配置

``` latex
\XeTeXlinebreaklocale{zh}
\XeTeXlinebreakskip=0em plus 0.1em minus 0.01em
\XeTeXlinebreakpenalty=0
```

网上找到的配置

> 其中的 \XeTeXlinebreaklocale 是表示 XeTeX 應該以中文的方式斷行，因為一般英文字只會在空白處斷行，而中文字除了避頭避尾以外可以斷在任何地方，因此要指定 XeTeX 使用中文方式斷行。後面的 \XeTeXlinebreakskip 則是讓 XeTeX 可以在字元間加入 0pt～1pt 的彈性間距，這樣才能排出左右切齊的文件。
> 
> ``` latex
> \XeTeXlinebreaklocale "zh"
> \XeTeXlinebreakskip = 0pt plus 1pt
> ```

**Comment by billie66** [comment]
http://tex.stackexchange.com/questions/43599/turning-chinese-line-breaks-on-and-off

**Comment by billie66** [comment]
通过启动中文断行方式，长链接和邮箱地址就能自动换行了
