### ISSUE TITLE
.vimrc part

### ISSUE THREAD

**Issue by digizeph** [happypeter/LGCB#7]
why not add some easy config examples, like `set nu` and some other basics. I think readers might like to create their own vimrc.

**Comment by happypeter** [comment]
Yes, I think I should add some tips to guide beginners making their own .vimrc. Good feekback , thanks! And you are welcomed if you want to add sth into this book yourself.

http://happypeter.github.com/LGCB/book/zh/

**Comment by happypeter** [comment]
https://github.com/happypeter/LGCB/issues/28
